contracts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from contracts import views


urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('contract/<int:pk>/', views.ContractView.as_view(), name='contract'),
    path('invoice/<int:pk>/', views.InvoiceView.as_view(), name='invoice'),
    path('invoice/new/', views.NewInvoiceView.as_view(), name='new_invoice'),
    path('contract/', views.ContractList.as_view(), name='contract_list'),
    path('invoice/', views.InvoiceList.as_view(), name='invoice_list'),
]

itfin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contracts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

contracts/models.py
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from djmoney.models.fields import MoneyField
from django.db import models
from django.urls import reverse
from contracts.constants import EXPENDITURES, SUBJECTS


class Vendor(models.Model):
    """Model for a vendor that sends invoices"""
    name = models.CharField(max_length=200, verbose_name=_("Vendor"))
    contact = models.TextField(blank=True, verbose_name=_("Contact"))

    class Meta:
        verbose_name = _("Vendor")
        verbose_name_plural = _("Vendors")

    def __str__(self):
        return "{}".format(self.name)


class Contract(models.Model):
    """Model for contracts that have to be continued on a rgualar basis"""

    name = models.CharField(max_length=200, verbose_name=_("Contract"))
    number = models.CharField(max_length=200, blank=True,
                              verbose_name=_("Order Number"))
    active = models.BooleanField(default=True, verbose_name=_("Active"))
    expenditure = models.CharField(max_length=1, choices=EXPENDITURES,
                                   blank=True, verbose_name=_("Expenditure"))
    subject = models.CharField(max_length=2, blank=True, choices=SUBJECTS,
                               verbose_name=_("Subject"))
    contract = models.FileField(blank=True, upload_to='contracts/',
                                verbose_name=_("Contract PDF"))
    comment = models.TextField(blank=True, verbose_name=_("Comment"))

    # Relationship fields
    vendor = models.ForeignKey(Vendor, default=1, on_delete=models.PROTECT,
                               verbose_name=_("Vendor"))

    class Meta:
        ordering = ['-active', 'name']
        verbose_name = _("Contract")
        verbose_name_plural = _("Contracts")

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('contract', args=[str(self.pk)])


class Budget(models.Model):
    """Yearly budget for Contracts"""

    valid_from = models.DateField(default=timezone.localdate,
                                  verbose_name=_("Begin date"))
    valid_for = models.SmallIntegerField(verbose_name=_("Validity in month"))
    value = MoneyField(max_digits=11, decimal_places=2, default_currency='EUR',
                       verbose_name=_("Value"))
    comment = models.TextField(blank=True, verbose_name=_("Comment"))

    # Relationship fields
    contract = models.ForeignKey(Contract, on_delete=models.PROTECT,
                                 verbose_name=_("Contract"))

    class Meta:
        verbose_name = _("Budget")
        verbose_name_plural = _("Budgets")

    def __str__(self):
        return "{} {}".format(self.valid_from, self.contract.name)


class Invoice(models.Model):
    """Model for received invoices"""

    name = models.CharField(max_length=200, verbose_name=_("Invoice"),
                            default=_("Invoice"))
    date = models.DateField(default=timezone.localdate,
                            verbose_name=_("Date of invoice"))
    value = MoneyField(max_digits=11, decimal_places=2, default_currency='EUR',
                       verbose_name=_("Value"))
    number = models.CharField(max_length=200, blank=True, default='--',
                              verbose_name=_("Order Number"))
    expenditure = models.CharField(max_length=1, choices=EXPENDITURES,
                                   blank=True, verbose_name=_("Expenditure"))
    subject = models.CharField(max_length=2, blank=True, choices=SUBJECTS,
                               verbose_name=_("Subject"))
    comment = models.TextField(blank=True, verbose_name=_("Comment"))

    # Relationship fields
    contract = models.ForeignKey(Contract, on_delete=models.SET_NULL,
                                 null=True, blank=True, default=None,
                                 verbose_name=_("Contract"))
    vendor = models.ForeignKey(Vendor, default=None, on_delete=models.SET_NULL,
                               null=True, blank=True, verbose_name=_("Vendor"))

    class Meta:
        ordering = ['-date']
        verbose_name = _("Invoice")
        verbose_name_plural = _("Invoices")

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('invoice', args=[str(self.pk)])

    def get_expenditure(self):
        if self.contract:
            return self.contract.expenditure
        else:
            return self.expenditure

    def get_subject(self):
        if self.contract:
            return self.contract.subject
        else:
            return self.subject


class NewDocumentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(invoice__isnull=True)


class InvoiceDocument(models.Model):
    """Model for the PDF document of received invoices"""

    name = models.CharField(max_length=50, verbose_name=_("Document"),
                            default=_("Invoice"))
    pdf = models.FileField(upload_to='invoices/',
                           verbose_name=_("PDF Document"))
    thumb = models.ImageField(upload_to='invoices/images/', editable=False,
                              verbose_name=_("PDF Preview"))
    modified = models.DateTimeField(auto_now=True,
                                    verbose_name=_("Date Modified"))

    # Relationship fields
    invoice = models.ForeignKey(Invoice, on_delete=models.SET_NULL, null=True,
                                default=None, related_name='documents',
                                verbose_name=_("Invoice"))

    # Custom manager
    objects = models.Manager()
    unassigned = NewDocumentManager()

    class Meta:
        ordering = ['-modified']
        verbose_name = _("Invoice Document")
        verbose_name_plural = _("Invoice Documents ")

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('invoice_pdf', args=[str(self.pk)])

contracts/views.py
from django.shortcuts import render
from django.views import generic
from contracts import models


# @login_required
def index(request):
    invoices = models.Invoice.objects.all()[:10]
    contracts = models.Contract.objects.filter(active=True)[:10]
    return render(request, 'contracts/index.html', context={
        'invoices': invoices, 'contracts': contracts})


class ContractView(generic.detail.DetailView):
    model = models.Contract


class InvoiceView(generic.detail.DetailView):
    model = models.Invoice


class NewInvoiceView(generic.edit.CreateView):
    model = models.Invoice
    fields = ['name', 'date', 'value', 'number', 'expenditure', 'subject',
              'comment', 'contract', 'vendor']
    raw_id_fields = ['documents']


class ContractList(generic.list.ListView):
    model = models.Contract


class InvoiceList(generic.list.ListView):
    model = models.Invoice

contracts/templates/base.html
{% load static from staticfiles %}
{% load i18n %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'contracts/css/base.css' %}">
    <title>IT Contracts</title>
  </head>
  <body>
    <div id="header">
      <nav class="navbar navbar-dark navbar-expand-md fixed-top">
        <div class="container">
          <a href="#" class="navbar-brand order-md-last">
            <img src='{% static "contracts/img/kronoslogo.svg" %}' alt="KRONOS" height="50">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="mainNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item homeLink" id="homeLink">
                <a href="/" class="nav-link">
                  <span aria-hidden="true" class="fa fa-spacer-right fa-home"></span>
                </a>
              </li>
              <li class="nav-item" id="invoiceLink">
                <a href="{% url 'invoice_list' %}" class="nav-link">
                  <!-- i class="fa fa-file-invoice-dollar fa-spacer-right"></i -->
                  {% trans "Invoices" %}
                </a>
              </li>
              <li class="nav-item" id="newInvoiceLink">
                <a href="{% url 'new_invoice' %}" class="nav-link">
                  <!-- i class="fa fa-file-invoice-dollar fa-spacer-right"></i -->
                  {% trans "New Invoice" %}
                </a>
              </li>
              <li class="nav-item" id="contractLink">
                <a href="{% url 'contract_list' %}" class="nav-link">
                  <!-- i class="fa fa-file-contract fa-spacer-right"></i -->
                  {% trans "Contracts" %}
                </a>
              </li>
              </li>
              <li class="nav-item adminLink" id="adminLink">
                <a href="/admin/" class="nav-link">
                  <!-- i class="fa fa-cog fa-spacer-right"></i -->
                  {% trans "Administration" %}
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div id="main">
      <div class="container">
        {% if messages %}{% for message in messages %}
        <div role="alert" class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show">
          <b>{% trans message.tags|upper %}</b><br>{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-labeled="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        {% endfor %} {% endif %}
        {% block base_content %}
        <h1>KRONOS IT Contracts</h1>
        {% endblock %}
      </div>
    </div>
     <div id="footer">
       <div class="container">
         <div class="content">
           <ul id="menu" class="menu">
             <li class="item-115"><a href="https://kronostio2.com/en/important-legal-information">Important Legal Information</a></li>
             <li class="item-669"><a href="https://kronostio2.com/en/terms-and-conditions">Terms and Conditions of Sale</a></li>
             <li class="item-116"><a href="https://kronostio2.com/en/privacy-policy">Privacy Policy</a></li>
           </ul>
           <br>
           <ul>
             <li>&copy; 2018 KRONOS Worldwide, Inc.</li>
             <li>5430 LBJ Freeway, Suite 1700</li>
             <li>Dallas, TX, 75240</li>
             <li>United States</li>
           </ul>
           <br>
           <ul>
             <li>Phone: (972) 233-1700</li>
             <li>Fax: (972) 448-1445</li>
             <li><a href="mailto:kronos.marketing@kronosww.com">kronos.marketing@kronosww.com</a></li>
           </ul>
         </div>
       </div>
     </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>
<!-- 
    vim:syntax=htmldjango:ts=2:sw=2:sts=2:nowrap
-->

contracts/templates/contracts/contract_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block base_content %}
<h1 class="mb-4">{% trans "IT Contract" %}</h1>
<table class="table">
    <thead>
        <tr>
            <th>{% trans "Contract" %}</th>
            <th>
                {% if object.contract %}
                <a href="{{ object.contract.url }}">
                    <i class="fas fa-file-pdf mr-1"></i>
                    {{ object.name }}
                </a>
                {% else %}
                {{ object.name }}
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>{% trans "Contract number" %}</th>
            <td>{{ object.number }}</td>
        </tr>
        <tr>
            <th>{% trans "Expenditures" %}</th>
            <td>
                {{ object.get_expenditure_display }}<br>
                {{ object.get_subject_display }}
            </td>
        </tr>
        <tr>
            <th>{% trans "Vendor" %}</th>
            <td>
                <p>
                    {{ object.vendor.name }}
                    <button class="btn btn-outline-primary btn-sm ml-5" type="button" data-toggle="collapse" data-target="#contact" aria-expand="false" aria-controls="contactCollapse" >
                        <i class="fas fa-address-card mr-1"></i>
                        {% trans "Toggle contact" %}
                    </button>
                </p>
                <div class="collapse" id="contact">
                    <div class="card">
                        <div class="card-body">
                            <pre>{{ object.vendor.contact }}</pre>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<h2 class="mb-4">{% trans "Invoices" %}</h2>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>{% trans "Invoice" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Value" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for invoice in object.invoice_set.all %}
        <tr>
            <td>
                <a href="{{ invoice.document.url }}">
                    <i class="fas fa-file-pdf mr-1"></i>
                    {{ invoice.name }}
                </a>
            </td>
            <td>{{ invoice.date }}</td>
            <td>{{ invoice.value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}
<!--
    vim:syntax=htmldjango
-->

contracts/templates/contracts/contract_list.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_js %}
<script>$('#contractLink').addClass('active')</script>
{% endblock %}

{% block base_content %}
<h1 class="mb-4">{% trans "IT Contracts" %}</h1>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>{% trans "Contract" %}</th>
            <th>{% trans "Order Number" %}</th>
            <th>{% trans "Vendor" %}</th>
            <th>{% trans "PDF" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {% if not object.active %}<s>{% endif %}
                    {{ object }}
                    {% if not object.active %}</s>{% endif %}
                </a>
            </td>
            <td>{{ object.number }}</td>
            <td>
                <a data-toggle="modal" data-target="#contact-{{ object.pk }}">
                    {{ object.vendor.name }}
                </a>
                <div class="modal fade" id="contact-{{ object.pk }}" tabindex="-1" role="dialog" aria-labelledby="label{{ object.pk }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="">
                                    {% trans "Contact" %} - 
                                    {{ object.vendor.name }}
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <pre>{{ object.vendor.contact }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td class="text-center">
                {% if object.contract %}
                <a href="{{ object.contract.url }}">
                    <i class="fas fa-file-pdf"></i>
                </a>
                {% else %}
                <i class="fas fa-times text-danger"></i>
                {% endif %}

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}
<!--
    vim:syntax=htmldjango
-->

contracts/templates/contracts/index.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_js %}
<script>$('#homeLink').addClass('active')</script>
{% endblock %}

{% block base_content %}
<h1 class="mb-4">{% trans "IT Invoices and Contracts" %}</h1>
<h3>{% trans "Latest Invoices" %}</h3>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>{% trans "Invoice" %}</th>
            <th>{% trans "Date" %}</th>
            <th class="d-none d-xl-table-cell">{% trans "Order Number" %}</th>
            <th class="d-none d-lg-table-cell">{% trans "Vendor" %}</th>
            <th>{% trans "Value" %}</th>
            <th>{% trans "PDF" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for object in invoices %}
        <tr>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </td>
            <td>{{ object.date }}</td>
            <td class="d-none d-xl-table-cell">{{ object.number }}</td>
            <td class="d-none d-lg-table-cell">
                <a data-toggle="modal" data-target="#contact-{{ object.pk }}">
                    {{ object.vendor.name }}
                </a>
                <div class="modal fade" id="contact-{{ object.pk }}" tabindex="-1" role="dialog" aria-labelledby="label{{ object.pk }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="">
                                    {% trans "Contact" %} - 
                                    {{ object.vendor.name }}
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <pre>{{ object.vendor.contact }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>{{ object.value }}</td>
            <td class="text-center">
                {% for document in object.documents.all %}
                    <a href="{{ document.pdf.url }}" title="{{ document.pdf.name }}">
                        <i class="fas fa-file-pdf"></i>
                    </a><br>
                {% empty %}
                    <i class="fas fa-times text-danger"></i>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<h3>{% trans "Available Contracts" %}</h3>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>{% trans "Contract" %}</th>
            <th class="d-none d-lg-table-cell">{% trans "Order Number" %}</th>
            <th>{% trans "Vendor" %}</th>
            <th>{% trans "PDF" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for object in contracts %}
        <tr>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </td>
            <td class="d-none d-lg-table-cell">{{ object.number }}</td>
            <td>
                <a data-toggle="modal" data-target="#contact-{{ object.pk }}">
                    {{ object.vendor.name }}
                </a>
                <div class="modal fade" id="contact-{{ object.pk }}" tabindex="-1" role="dialog" aria-labelledby="label{{ object.pk }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="">
                                    {% trans "Contact" %} - 
                                    {{ object.vendor.name }}
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <pre>{{ object.vendor.contact }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td class="text-center">
                {% if object.contract %}
                <a href="{{ object.contract.url }}">
                    <i class="fas fa-file-pdf"></i>
                </a>
                {% else %}
                <i class="fas fa-times text-danger"></i>
                {% endif %}

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}
<!--
    vim:syntax=htmldjango
-->

contracts/templates/contracts/invoice_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block base_content %}
<h1 class="mb-4">{% trans "IT Invoice" %}</h1>
<table class="table">
    <tbody>
        <tr>
            <th>{% trans "Invoices" %}</th>
            <th>
                {% for document in object.documents.all %}
                    <a href="{{ document.pdf.url }}" title="{{ document.pdf.name }}">
                        <i class="fas fa-file-pdf"></i>
                        {{ document.pdf.name }}
                    </a><br>
                {% empty %}
                    <i class="fas fa-times text-danger"></i>
                {% endfor %}
            </th>
        </tr>
        <tr>
            <th>{% trans "Invoice number" %}</th>
            <td>{{ object.number }}</td>
        </tr>
        <tr>
            <th>{% trans "Expenditures" %}</th>
            <td>
                {{ object.get_expenditure_display }}<br>
                {{ object.get_subject_display }}
            </td>
        </tr>
        <tr>
            <th>{% trans "Vendor" %}</th>
            <td>
                <p>
                    {{ object.vendor.name }}
                    <button class="btn btn-outline-primary btn-sm ml-5" type="button" data-toggle="collapse" data-target="#contact" aria-expanded="false" aria-controls="contactCollapse" >
                        <i class="fas fa-address-card mr-1"></i>
                        {% trans "Toggle contact" %}
                    </button>
                </p>
                <div class="collapse" id="contact">
                    <div class="card">
                        <div class="card-body">
                            <pre>{{ object.vendor.contact }}</pre>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

{% endblock %}
<!--
    vim:syntax=htmldjango
-->

contracts/templates/contracts/invoice_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_js %}
<script>
    $('#newInvoiceLink').addClass('active');
    $('#id_value_0').parent().addClass("row");
    $('#id_value_0').addClass("form-control");
    $('#id_value_0').wrap("<div class='col'></div>");
    $('#id_value_1').addClass("form-control");
    $('#id_value_1').wrap("<div class='col'></div>");
</script>
{% endblock %}

{% block base_content %}
<h1 class="mb-4">{% trans "New IT Invoice" %}</h1>

<button class="btn btn-outline-primary btn-sm mb-3" type="button"
    data-toggle="collapse" data-target=".contractCollapse"
    aria-controls="contractCollapse invoiceCollapse">
    {% trans "Toggle Contract / Single Invoice" %}
</button>

<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            {{ form.name|as_crispy_field }}
            <div class="contractCollapse collapse" id="invoiceCollapse">
                {{ form.vendor|as_crispy_field }}
            </div>
        </div>
        <div class="col">
            <div class="contractCollapse collapse show" id="contractCollapse">
                {{ form.contract|as_crispy_field }}
            </div>
            <div class="contractCollapse collapse" id="invoiceCollapse">
                {{ form.expenditure|as_crispy_field }}
                {{ form.subject|as_crispy_field }}
            </div>
        </div>
    </div>
    <div class="form-group mt-2 mb-4">
        {{ form.docuemts|as_crispy_field }}
    </div>
    <div class="row">
        <div class="col">
            {{ form.date|as_crispy_field }}
            {{ form.value|as_crispy_field }}
            {{ form.number|as_crispy_field }}
        </div>
        <div class="col">
            {{ form.comment|as_crispy_field }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</form>

{% endblock %}
<!--
    vim:syntax=htmldjango
-->

contracts/templates/contracts/invoice_list.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_js %}
<script>$('#invoiceLink').addClass('active')</script>
{% endblock %}

{% block base_content %}
<h1 class="mb-4">{% trans "IT Invoices" %}</h1>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>{% trans "Invoice" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Order Number" %}</th>
            <th>{% trans "Vendor" %}</th>
            <th>{% trans "Value" %}</th>
            <th>{% trans "PDF" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </td>
            <td>{{ object.date }}</td>
            <td>{{ object.number }}</td>
            <td>
                <a data-toggle="modal" data-target="#contact-{{ object.pk }}">
                    {{ object.vendor.name }}
                </a>
                <div class="modal fade" id="contact-{{ object.pk }}" tabindex="-1" role="dialog" aria-labelledby="label{{ object.pk }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="">
                                    {% trans "Contact" %} - 
                                    {{ object.vendor.name }}
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <pre>{{ object.vendor.contact }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>{{ object.value }}</td>
            <td class="text-center">
                {% for document in object.documents.all %}
                    <a href="{{ document.pdf.url }}" title="{{ document.pdf.name }}">
                        <i class="fas fa-file-pdf"></i>
                    </a><br>
                {% empty %}
                    <i class="fas fa-times text-danger"></i>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
<!--
    vim:syntax=htmldjango
-->